apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: clase12
  namespace: clase12
spec:
  ports:
    - port: 80
  selector:
    app: clase12
    tier: frontend
  clusterIP: None
